export const currencies = [
  {
    name: 'US Dollar',
    code: 'USD',
    symbol: '$',
  },
  {
    name: 'Euro',
    code: 'EUR',
    symbol: '€',
  },
  {
    name: 'British Pound',
    code: 'GBP',
    symbol: '£',
  },
  {
    name: 'Bitcoin',
    code: 'BTC',
    symbol: '₿',
  },
  {
    name: 'Bitcoin satoshis',
    code: 'sat',
    symbol: 'sats',
  },
  {
    name: 'Japanese Yen',
    code: 'JPY',
    symbol: '¥',
  },
  {
    name: 'Australian Dollar',
    code: 'AUD',
    symbol: '$',
  },
  {
    name: 'Canadian Dollar',
    code: 'CAD',
    symbol: '$',
  },
  {
    name: 'Swiss Franc',
    code: 'CHF',
    symbol: 'CHF',
  },
  {
    name: 'Chinese Yuan',
    code: 'CNY',
    symbol: '¥',
  },
  {
    name: 'Swedish Krona',
    code: 'SEK',
    symbol: 'kr',
  },
  {
    name: 'New Zealand Dollar',
    code: 'NZD',
    symbol: '$',
  },
  {
    name: 'Mexican Peso',
    code: 'MXN',
    symbol: '$',
  },
  {
    name: 'Singapore Dollar',
    code: 'SGD',
    symbol: '$',
  },
  {
    name: 'Hong Kong Dollar',
    code: 'HKD',
    symbol: '$',
  },
  {
    name: 'Norwegian Krone',
    code: 'NOK',
    symbol: 'kr',
  },
  {
    name: 'South Korean Won',
    code: 'KRW',
    symbol: '₩',
  },
  {
    name: 'Turkish Lira',
    code: 'TRY',
    symbol: '₺',
  },
  {
    name: 'Russian Ruble',
    code: 'RUB',
    symbol: '₽',
  },
  {
    name: 'Indian Rupee',
    code: 'INR',
    symbol: '₹',
  },
  {
    name: 'Brazilian Real',
    code: 'BRL',
    symbol: 'R$',
  },
  {
    name: 'South African Rand',
    code: 'ZAR',
    symbol: 'R',
  },
  {
    name: 'Philippine Peso',
    code: 'PHP',
    symbol: '₱',
  },
  {
    name: 'Polish Zloty',
    code: 'PLN',
    symbol: 'zł',
  },
  {
    name: 'Czech Koruna',
    code: 'CZK',
    symbol: 'Kč',
  },
  {
    name: 'Danish Krone',
    code: 'DKK',
    symbol: 'kr',
  },
  {
    name: 'Hungarian Forint',
    code: 'HUF',
    symbol: 'Ft',
  },
  {
    name: 'Israeli New Sheqel',
    code: 'ILS',
    symbol: '₪',
  },
  {
    name: 'Icelandic Króna',
    code: 'ISK',
    symbol: 'kr',
  },
  {
    name: 'Croatian Kuna',
    code: 'HRK',
    symbol: 'kn',
  },
  {
    name: 'Romanian Leu',
    code: 'RON',
    symbol: 'lei',
  },
  {
    name: 'Thai Baht',
    code: 'THB',
    symbol: '฿',
  },
  {
    name: 'Indonesian Rupiah',
    code: 'IDR',
    symbol: 'Rp',
  },
  {
    name: 'Malaysian Ringgit',
    code: 'MYR',
    symbol: 'RM',
  },
  {
    name: 'New Taiwan Dollar',
    code: 'TWD',
    symbol: 'NT$',
  },
  {
    name: 'Chilean Peso',
    code: 'CLP',
    symbol: '$',
  },
  {
    name: 'Saudi Riyal',
    code: 'SAR',
    symbol: '﷼',
  },
  {
    name: 'UAE Dirham',
    code: 'AED',
    symbol: 'د.إ',
  },
  {
    name: 'Argentine Peso',
    code: 'ARS',
    symbol: '$',
  },
  {
    name: 'Colombian Peso',
    code: 'COP',
    symbol: '$',
  },
  {
    name: 'Venezuelan Bolívar',
    code: 'VEF',
    symbol: 'Bs',
  },
  {
    name: 'Bolivian Boliviano',
    code: 'BOB',
    symbol: 'Bs',
  },
  {
    name: 'Peruvian Sol',
    code: 'PEN',
    symbol: 'S/',
  },
  {
    name: 'Uruguayan Peso',
    code: 'UYU',
    symbol: '$',
  },
  {
    name: 'Costa Rican Colón',
    code: 'CRC',
    symbol: '₡',
  },
  {
    name: 'Dominican Peso',
    code: 'DOP',
    symbol: 'RD$',
  },
  {
    name: 'Paraquayan Guarani',
    code: 'PYG',
    symbol: '₲',
  },
  {
    name: 'Tanazanian Shilling',
    code: 'TZS',
    symbol: 'TSh',
  },
  {
    name: 'Barbados Dollar',
    code: 'BBD',
    symbol: '$',
  },
  {
    name: 'Fiji Dollar',
    code: 'FJD',
    symbol: '$',
  },
  {
    name: 'Jamaican Dollar',
    code: 'JMD',
    symbol: '$',
  },
  {
    name: 'Kenyan Shilling',
    code: 'KES',
    symbol: 'KSh',
  },
  {
    name: 'Moldovan Leu',
    code: 'MDL',
    symbol: 'L',
  },
  {
    name: 'Bermudian Dollar',
    code: 'BMD',
    symbol: '$',
  },
  {
    name: 'Falkland Islands Pound',
    code: 'FKP',
    symbol: '£',
  },
  {
    name: 'Gibraltar Pound',
    code: 'GIP',
    symbol: '£',
  },
  {
    name: 'Bulgarian Lev',
    code: 'BGN',
    symbol: 'лв',
  },
];

export enum CurrencyCode {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  BTC = 'BTC',
  sat = 'sat',
  JPY = 'JPY',
  AUD = 'AUD',
  CAD = 'CAD',
  CHF = 'CHF',
  CNY = 'CNY',
  SEK = 'SEK',
  NZD = 'NZD',
  MXN = 'MXN',
  SGD = 'SGD',
  HKD = 'HKD',
  NOK = 'NOK',
  KRW = 'KRW',
  TRY = 'TRY',
  RUB = 'RUB',
  INR = 'INR',
  BRL = 'BRL',
  ZAR = 'ZAR',
  PHP = 'PHP',
  PLN = 'PLN',
  CZK = 'CZK',
  DKK = 'DKK',
  HUF = 'HUF',
  ILS = 'ILS',
  ISK = 'ISK',
  HRK = 'HRK',
  RON = 'RON',
  THB = 'THB',
  IDR = 'IDR',
  MYR = 'MYR',
  TWD = 'TWD',
  CLP = 'CLP',
  SAR = 'SAR',
  AED = 'AED',
  ARS = 'ARS',
  COP = 'COP',
  VEF = 'VEF',
  BOB = 'BOB',
  PEN = 'PEN',
  UYU = 'UYU',
  CRC = 'CRC',
  DOP = 'DOP',
  PYG = 'PYG',
  TZS = 'TZS',
  BBD = 'BBD',
  FJD = 'FJD',
  JMD = 'JMD',
  KES = 'KES',
  MDL = 'MDL',
  BMD = 'BMD',
  FKP = 'FKP',
  GIP = 'GIP',
  BGN = 'BGN',
}
